//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportsFacility4A
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTransaction
    {
        public int BookingID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> VenueID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<System.DateTime> BookedDate { get; set; }
        public string BookedHour { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Venue Venue { get; set; }
    }
}
